DjangoPass/learning_users/basicapp/urls.py
from django.conf.urls import url
from basicapp import views


app_name='basicapp'
urlpatterns=[
    url('register/',views.register,name='register'),
    url('user_login/', views.user_login, name='user_login')

]

DjangoPass/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('logout/',views.user_logout,name='logout'),
    path('special/', views.special,name='special'),
    path('basicapp/', include('basicapp.urls'))
]

DjangoPass/learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    protfolio=models.URLField(blank=True)
    profilePic=models.ImageField(upload_to='profile_pics',blank=True)


    def __str__(self):
        return self.user.username

DjangoPass/learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class userform(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields = ('username','email','password')

class UserProfile(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('protfolio','profilePic')

DjangoPass/learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import userform,UserProfile
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse


def index(request):
    return render(request,'basicapp/index.html')
@login_required
def special(request):
    return HttpResponse("Logged In")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered=False

    if request.method =="POST":
        user_form=userform(data=request.POST)
        profile_form=UserProfile(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pics' in request.FILES:
                profile.profile_pic=request.Files['profile_pics']

            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)

    else:
         user_form=userform()
         profile_form=UserProfile()

    return render(request,'basicapp/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})
def user_login(request):

    if request.method=='POST':
      username=request.POST.get('username')
      password=request.POST.get('password')
      user=authenticate(username=username,password=password)

      if user:
        if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
        else:
          return HttpResponse("Account not active")
      else:
         return HttpResponse("invalid username and password")
    else:
        return render(request,'basicapp/login.html',{})

DjangoPass/learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{%url 'index' %}">DJANGO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Brand</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'basicapp:register'%}" >Register</a>
      </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link " href="{% url 'logout'%}" >Logout</a>
      </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link " href="{% url 'basicapp:user_login'%}" >Login</a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>
<div class="container">
    {% block body_block%}

    {% endblock %}
</div>

</body>
</html>

DjangoPass/learning_users/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<h1>

    welcome to HomePage
</h1>
{% endblock %}

DjangoPass/learning_users/templates/basicapp/login.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}

{% block body_block %}
<div class="jumbotron">
    <h1>LOGIN HERE </h1>
    <form action="{% url 'basicapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username" >USERNAME:</label>
        <input name="username" type="text" placeholder="Enter username">

         <label for="password" >PASSWORD:</label>
        <input name="password" type="password" placeholder="Enter password">

        <input type="submit" value="Login">
    </form>

 </div>


{% endblock %}

DjangoPass/learning_users/templates/basicapp/registration.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}


{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thanku for Registering</h1>
    {% else %}
<h1>
    FillUp The Form
</h1>
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p}}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
</form>
{% endif %}

{% endblock %}
    </div>